# Generated by Django 3.1 on 2023-12-26 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_reviewrating_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
