# Generated by Django 3.1 on 2023-12-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.AlterModelOptions(
            name='variations',
            options={'verbose_name': 'variations', 'verbose_name_plural': 'variations'},
        ),
    ]
